import {navigation,categories,licenses,regions} from './content.js';
export const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults={language:'ru',theme:'light',a11y:false,palette:'light',fontScale:1,hideImages:false};
export let preferences={...defaults};
try{preferences={...defaults,...JSON.parse(localStorage.getItem('roof.preferences')||'{}')};}catch{}
export const tr=(ru,en)=>preferences.language==='en'?en:ru;
export const textOf=(o,k='title')=>o[preferences.language==='en'?`${k}En`:k]||o[k]||'';
export const asset=name=>`${import.meta.env.BASE_URL}assets/${name}`;
export function image(path,alt,cls='',attrs=''){return `<img src="${escapeHTML(path.startsWith('assets/')?import.meta.env.BASE_URL+path:asset(path))}" alt="${escapeHTML(alt)}" class="${cls}" ${attrs}><span class="image-description">${escapeHTML(alt)}</span>`;}
export const icon=(name,extra='')=>`<img src="${asset(name)}" class="icon ${extra}" alt="" width="24" height="24">`;
export const routeLink=(path,ru,en,cls='')=>`<a href="#/${path}" class="${cls}">${tr(ru,en)}</a>`;
export function applyPreferences(){const r=document.documentElement;r.lang=preferences.language;r.dataset.theme=preferences.theme;r.dataset.a11y=String(preferences.a11y);r.dataset.palette=preferences.palette;r.dataset.hideImages=String(preferences.hideImages);r.style.setProperty('--font-scale',preferences.fontScale);try{localStorage.setItem('roof.preferences',JSON.stringify(preferences));}catch{}}
export function setPreferences(changes){Object.assign(preferences,changes);applyPreferences();}
export function resetPreferences(){preferences={...defaults};applyPreferences();localStorage.clear();}
export function header(home=false){return `<header class="header ${home?'home-header':''}"><a class="brand" href="#/" aria-label="${tr('Руф Профи — главная','Roof Profi — home')}"><img src="${asset('imgLogo.png')}" alt="" width="50" height="40"><span>${tr('Руф Профи','Roof Profi')}</span></a><nav class="desktop-nav" aria-label="${tr('Основная навигация','Main navigation')}">${navigation.map(([p,r,e],i)=>i===0?`<div class="nav-dropdown">${routeLink(p,r,e)}<div class="nav-submenu">${routeLink('account','Личный кабинет','My account')}${routeLink('settings','Настройки сайта','Site settings')}</div></div>`:routeLink(p,r,e)).join('')}</nav><div class="header-contacts"><a href="tel:+78462541373">+7 (846) 254-13-73</a><a href="mailto:info@roof-prof.ru">info@roof-prof.ru</a></div><div class="mobile-controls"><a class="icon-button" href="tel:+78462541373" aria-label="${tr('Позвонить','Call us')}">☎</a><button class="icon-button" data-action="menu" aria-label="${tr('Открыть меню','Open menu')}" aria-expanded="false"><span class="burger-glyph" aria-hidden="true"></span></button></div></header>`;}
export function mobileMenu(){return `<div class="mobile-menu" id="mobile-menu"><nav>${navigation.map(([p,r,e])=>routeLink(p,r,e)).join('')}${routeLink('account','Личный кабинет','My account')}${routeLink('settings','Настройки сайта','Site settings')}</nav><div class="menu-contacts"><a href="tel:+78462541373">+7 (846) 254-13-73</a><a href="mailto:info@roof-prof.ru">info@roof-prof.ru</a><p>${tr('443111, Россия, г. Самара, ул. Урицкого 19, офис 502','19 Uritskogo Street, office 502, Samara, Russia')}</p></div><div class="menu-actions"><button class="button" data-request="partner">${tr('Предложить партнёрство','Propose a partnership')}</button><button class="button secondary" data-request="question">${tr('Задать вопрос','Ask a question')}</button></div></div>`;}
export function footer(home=false){return `<footer class="site-footer"><div class="footer-banner"><p>${tr('Строим будущее<span>уже сегодня</span>','Building the future<span>starting today</span>')}</p></div><div class="footer-main"><div class="footer-top"><div><a class="footer-brand" href="#/"><img src="${asset('imgLogo.png')}" alt="" width="72" height="57"><span>${tr('Руф Профи','Roof Profi')}</span></a><div class="footer-contacts"><a class="phone" href="tel:+78462541373">+7 (846) 254-13-73</a><p>${tr('443111, Россия, г. Самара, ул. Урицкого 19, офис 502','19 Uritskogo Street, office 502, Samara, Russia')}</p><a href="mailto:info@roof-prof.ru">info@roof-prof.ru</a></div></div><div><div class="footer-links"><div><strong>${tr('Сферы деятельности','Our expertise')}</strong><ul>${categories.map(c=>`<li><a href="#/projects?category=${c.id}">${tr(c.ru,c.en)}</a></li>`).join('')}</ul></div><ul class="other-links">${navigation.filter(x=>x[0]!=='services').map(([p,r,e])=>`<li>${routeLink(p,p==='projects'?'Реализованные объекты':p==='licenses'?'Лицензии и сертификаты':r,e)}</li>`).join('')}</ul></div><div class="footer-actions"><button data-request="partner">${icon('imgVuesaxLinearArrowRight.svg')}${tr('Предложить партнерство','Propose a partnership')}</button><button data-request="question">${icon('imgVuesaxLinearArrowRight.svg')}${tr('Задать вопрос','Ask a question')}</button></div></div></div><div class="footer-bottom"><p>${tr('© 2022. ООО «Руф Профи»','© 2022. Roof Profi LLC')}</p>${routeLink('agreement','Политика конфиденциальности','Privacy policy')}<p>${tr('Разработка сайта Varnoff Studio','Website design by Varnoff Studio')}</p></div></div>${home?'':`<div class="utility-bar"><nav>${routeLink('account','Личный кабинет','My account')}${routeLink('settings','Настройки сайта','Site settings')}</nav><button data-action="language">${preferences.language==='ru'?'English':'Русский'}</button></div>`}</footer>`;}
export function innerHero(ru,en,name='45-3130-imgInnerHeadDesktop.png'){return `${header()}<div class="inner-hero">${image(name,'','','fetchpriority="high"')}<h1>${tr(ru,en)}</h1></div><nav class="breadcrumbs" aria-label="${tr('Хлебные крошки','Breadcrumbs')}">${routeLink('','Главная','Home')}<span aria-hidden="true">/</span><span>${tr(ru,en)}</span></nav>`;}
export function facts(p){const c=categories.find(c=>c.id===p.category);return `<dl>${[[tr('Направление','Sector'),tr(c?.short||'',c?.en||'')],[tr('Срок реализации','Project period'),`${p.dateFrom.split('-').reverse().join('.')} – ${p.dateTo.split('-').reverse().join('.')}`],[tr('Заказчик','Client'),textOf(p,'client')],[tr('Местоположение','Location'),textOf(p,'location')]].map(([k,v])=>`<div><dt>${k}</dt><dd>${escapeHTML(v)}</dd></div>`).join('')}</dl>`;}
export function projectCard(p,home=false){return `<article class="project-card"><a href="#/project/${encodeURIComponent(p.id)}">${image(p.image,textOf(p),'project-image','loading="lazy"')}<h3>${textOf(p).split("\n").map(part=>`<span>${escapeHTML(part)}</span>`).join("")}</h3></a>${facts(p)}${home?'':`<div class="project-actions"><button data-favorite="${escapeHTML(p.id)}" aria-pressed="false">${tr('В избранное','Save project')}</button></div>`}</article>`;}
export function statistics(){const rows=[['11','Лет стабильной работы','Years of steady work','Компания официально начала работу 27\u00a0июля 2011 года.','The company officially began operations on 27 July 2011.'],['290','Сотрудников','Employees','Каждый из которых является профессионалом в своей области.','Each is a professional in their field.'],['54','Реализованных объекта','Completed projects','Объекты Руф Профи расположены по всей территории Российской Федерации.','Roof Profi projects are located throughout the Russian Federation.']];return `<div class="statistics">${rows.map(([n,r,e,dr,de])=>`<div class="stat"><strong class="stat-number">${n}</strong><div><h3>${tr(r,e)}</h3><p>${tr(dr,de)}</p></div></div>`).join('')}</div><div class="geography"><h3>${tr('Реализованные объекты на\u00a0территориях:','Completed projects across the regions:')}</h3><div class="map-content"><img class="russia-map" src="${asset('imgG7028.svg')}" alt="${tr('Карта регионов работы компании','Map of the company’s project regions')}"><ul class="region-list">${regions.map(([r,e])=>`<li>${icon('imgFrame.svg')}${tr(r,e)}</li>`).join('')}</ul><div class="map-note"><div class="symbols">${['imgFlag.svg','img3Dcube.svg','imgTask.svg'].map(n=>`<img src="${asset(n)}" alt="" width="64" height="64">`).join('')}</div><p>${tr('Везде можно встретить бренд Руф\u00a0Профи, являющийся несомненным знаком качества выполняемых и уже выполненных работ.','The Roof Profi brand stands for quality in every project, from the first stage to completion.')}</p></div></div></div>`;}
export function licenseList(){return `<div class="license-columns">${[licenses.slice(0,5),licenses.slice(5)].map(list=>`<ul class="license-list">${list.map(l=>`<li><a href="#/licenses" data-license="${l.id}">${icon('imgVuesaxLinearDocumentText.svg')}${tr(l.ru,l.en)}</a></li>`).join('')}</ul>`).join('')}</div>`;}
export function field(name,ru,en,{type='text',required=true,autocomplete='',full=false,extra='',value=''}={}){return `<label class="field ${full?'full':''}"><span>${tr(ru,en)}${required?' *':''}</span><input name="${name}" type="${type}" ${required?'required':''} ${autocomplete?`autocomplete="${autocomplete}"`:''} value="${escapeHTML(value)}" aria-describedby="error-${name}" ${extra}><span class="field-error" id="error-${name}" data-error="${name}"></span></label>`;}
export function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),4500);}
let previouslyFocused;
export function openModal(content){const d=document.querySelector('#modal');previouslyFocused=document.activeElement;d.innerHTML=`<button class="dialog-close" data-action="close">× ${tr('Закрыть','Close')}</button><div class="dialog-content">${content}</div>`;document.body.classList.add('modal-open');if(!d.open)d.showModal();d.addEventListener('close',()=>{document.body.classList.remove('modal-open');previouslyFocused?.focus?.();},{once:true});}
export function closeModal(){document.querySelector('#modal').close();}
export const loading=()=>`<div class="loading" role="status"><span class="spinner" aria-hidden="true"></span><p>${tr('Загружаем данные…','Loading…')}</p></div>`;
export const empty=(ru,en)=>`<div class="empty-state"><h2>${tr(ru,en)}</h2><p>${tr('Попробуйте изменить параметры поиска.','Try changing your search criteria.')}</p></div>`;
